// react-cra-ts/src/App.tsx
import { ReactComponent as MonkeySvg} from "./assets/monkey.svg"
import { ReactComponent as ReactSvg} from './assets/react.svg'
import { ReactComponent as TypescriptSvg } from "./assets/typescript.svg"
import './App.css';

export default function App() {
  return (
    <div className='main'>
      <div className='content'>
        <div className='inner-content'>
          <MonkeySvg className="monkey"/>

          <div className='tech-container'>
            <ReactSvg/>
            <TypescriptSvg/>
          </div>

          <div className='description-container'>
            <header className='header'>
              React + Typescript
            </header>
            <p className='description'>
              Congrats! You've reached the first page of your website. To customize anything on this site, simply go ahead and make changes to your files via t.Webpages.
            </p>
          </div>
        </div>  
      </div>
    </div>
  );
};

// svelte-ts/src/App.svelte
<script>
	import "./App.css"
	import MonkeySvg from "./assets/monkeySvg.svelte";
	import SvelteSvg from "./assets/svelteSvg.svelte"
	import TypescriptSvg from "./assets/typescriptSvg.svelte";
</script>

<main>
	<div class='main'>
		<div class='content'>
			<div class='inner-content'>
				<MonkeySvg/>
	
				<div class='tech-container'>
					<SvelteSvg/>
					<TypescriptSvg/>
				</div>
	
				<div class='description-container'>
					<header class='header'>
						Svelte + Typescript
					</header>
					<p class='description'>
						{"Congrats! You've reached the first page of your website. To customize anything on this site, simply go ahead and make changes to your files via t.Webpages."}
					</p>
				</div>
			</div>  
		</div>
	</div>
</main>
