// svelte-vite-ts/src/App.svelte
<script>
	import "./App.css"
	import MonkeySvg from "./assets/monkeySvg.svelte"
	import TypescriptSvg from "./assets/typescriptSvg.svelte";
	import SvelteSvg from "./assets/svelteSvg.svelte"
	import ViteSvg from "./assets/viteSvg.svelte"

</script>

<main>
	<div class='main'>
		<div class='content'>
			<div class='inner-content'>
				<MonkeySvg class="monkey"/>
	
				<div class='tech-container'>
					<ViteSvg/>
					<SvelteSvg/>
					<TypescriptSvg/>
				</div>
	
				<div class='description-container'>
					<header class='header'>
						Vite + Svelte + TS
					</header>
					<p class='description'>
						{"Congrats! You've reached the first page of your website. To customize anything on this site, simply go ahead and make changes to your files via t.Webpages."}
					</p>
				</div>
			</div>  
		</div>
	</div>
</main>

// react-vite-ts/src/App.tsx
import MonkeySvg from './assets/monkey.svg?react'
import ReactSvg from './assets/react.svg?react'
import ViteSvg from './assets/vite.svg?react'
import TypescriptSvg from './assets/typescript.svg?react'
import './App.css';

export default function App() {
  return (
    <div className='main'>
      <div className='content'>
        <div className='inner-content'>
          <MonkeySvg className="monkey"/>

          <div className='tech-container'>
            <ViteSvg/>
            <ReactSvg/>
            <TypescriptSvg/>
          </div>

          <div className='description-container'>
            <header className='header'>
              Vite + React + Typescript
            </header>
            <p className='description'>
              Congrats! You've reached the first page of your website. To customize anything on this site, simply go ahead and make changes to your files via t.Webpages.
            </p>
          </div>
        </div>  
      </div>
    </div>
  );
};
