// vuejs/src/App.vue
<template>
  <main>
    <div class='main'>
      <div class='content'>
        <div class='inner-content'>
          <img class="monkey" src="./assets/monkey.svg"/>
    
          <div class='tech-container'>
            <img src="./assets/vue.svg"/>
            <img src="./assets/javascript.svg"/>
          </div>
    
          <div class='description-container'>
            <header class='header'>
              Vue + JS
            </header>
            <p class='description'>
              Congrats! You've reached the first page of your website. To customize anything on this site, simply go ahead and make changes to your files via t.Site.
            </p>
          </div>
        </div>  
      </div>
    </div>
  </main>
</template>

<style>
  @import "./App.css";
</style>

// react-cra/src/App.jsx
import React from 'react';
import './App.css';
import {ReactComponent as MonkeySvg} from './assets/monkey.svg'
import {ReactComponent as ReactSvg} from './assets/react.svg'
import {ReactComponent as JavascriptSvg} from './assets/javascript.svg'

export default function App() {
  return (
    <div className='main'>
      <div className='content'>
        <div className='inner-content'>
          <MonkeySvg className="monkey"/>

          <div className='tech-container'>
            <ReactSvg/>
            <JavascriptSvg/>
          </div>

          <div className='description-container'>
            <header className='header'>
              React + JS
            </header>
            <p className='description'>
              Congrats! You've reached the first page of your website. To customize anything on this site, simply go ahead and make changes to your files via t.Site.
            </p>
          </div>
        </div>  
      </div>
    </div>
  );
}
