// svelte/src/App.svelte
<script>
	import "./App.css"
	import MonkeySvg from "./assets/monkeySvg.svelte";
	import JavascriptSvg from "./assets/javascriptSvg.svelte";
	import SvelteSvg from "./assets/svelteSvg.svelte"
</script>

<main>
	<div class='main'>
		<div class='content'>
			<div class='inner-content'>
				<MonkeySvg/>
	
				<div class='tech-container'>
					<SvelteSvg/>
					<JavascriptSvg/>
				</div>
	
				<div class='description-container'>
					<header class='header'>
						Svelte + JS
					</header>
					<p class='description'>
						{"Congrats! You've reached the first page of your website. To customize anything on this site, simply go ahead and make changes to your files via t.Webpages."}
					</p>
				</div>
			</div>  
		</div>
	</div>
</main>

// react-cra/src/App.jsx
import React from 'react';
import './App.css';
import {ReactComponent as MonkeySvg} from './assets/monkey.svg'
import {ReactComponent as ReactSvg} from './assets/react.svg'
import {ReactComponent as JavascriptSvg} from './assets/javascript.svg'

export default function App() {
  return (
    <div className='main'>
      <div className='content'>
        <div className='inner-content'>
          <MonkeySvg className="monkey"/>

          <div className='tech-container'>
            <ReactSvg/>
            <JavascriptSvg/>
          </div>

          <div className='description-container'>
            <header className='header'>
              React + JS
            </header>
            <p className='description'>
              Congrats! You've reached the first page of your website. To customize anything on this site, simply go ahead and make changes to your files via t.Webpages.
            </p>
          </div>
        </div>  
      </div>
    </div>
  );
}
